export const CART_SAVE_SHIPPING_ADDRESS_REQUEST = "CART_SAVE_SHIPPING_ADDRESS_REQUEST";
export const CART_SAVE_SHIPPING_ADDRESS_SUCCESS = "CART_SAVE_SHIPPING_ADDRESS_SUCCESS";
export const CART_SAVE_SHIPPING_ADDRESS_FAIL = "CART_SAVE_SHIPPING_ADDRESS_FAIL";
export const CART_SHIPPING_ADDRESS_REQUEST = "CART_SHIPPING_ADDRESS_REQUEST";
export const CART_SHIPPING_ADDRESS_SUCCESS = "CART_SHIPPING_ADDRESS_SUCCESS";
export const CART_SHIPPING_ADDRESS_FAIL = "CART_SHIPPING_ADDRESS_FAIL";
